name: "CI"
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - uses: coursier/cache-action@v6
      - uses: coursier/setup-action@v1
      - name: Run tests
        run: sbtn test
